title: 4PM
description: 几个荷区产品人的闲聊出品
author: Rebi
email: april.lihan.94@gmail.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2020"
logo: /assets/img/4PM_demo.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
